"""initial jobs and job_files

Revision ID: b0218fcfc4ac
Revises: 
Create Date: 2026-08-09 08:51:47.024837

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b0218fcfc4ac'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'PARTIAL', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('output_dir', sa.String(length=1024), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('job_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('input_path', sa.String(length=1024), nullable=False),
    sa.Column('output_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'PARTIAL', 'FAILED', name='filestatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('parent_count', sa.Integer(), nullable=False),
    sa.Column('child_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('parent_strategy', sa.String(length=32), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_files_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_files_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_files_status'))
        batch_op.drop_index(batch_op.f('ix_job_files_job_id'))

    op.drop_table('job_files')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))

    op.drop_table('jobs')
    # ### end Alembic commands ###
